---
- hosts: web

  tasks:
  - name: Add User
    user: name={{username}} password={{password}} createhome=yes shell=/bin/bash

  - name: Create www folder
    file: path=/home/{{username}}/www/ state=directory

  #Install Base packages

  - name: Install Nginx
    apt: name='nginx' state='present' update_cache=yes

  - name: Remove default Vhost
    file: path={{item}} state=absent
    with_items:
      - /etc/nginx/sites-available/default
      - /etc/nginx/sites-enabled/default

  - name: Write nginx.conf 
    template: src=templates/nginx.j2 dest=/etc/nginx/nginx.conf
    notify:
    - restart nginx

  - name: Add Vhost
    template: src=templates/vhost.j2 dest=/etc/nginx/sites-enabled/vhost
    notify:
    - restart nginx

  handlers:
    - name: restart nginx
      action: service name=nginx state=restarted
